# Generated by Django 4.1.4 on 2023-01-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
