# Generated by Django 4.1.4 on 2023-01-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
