# Generated by Django 4.1.4 on 2023-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
